ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG PACKAGE
RUN useradd -d /home/nonroot-user -g 1001 -u 1001 -s /bin/bash nonroot-user
RUN dnf install -y "$PACKAGE" && dnf clean all && rm /var/log/dnf.librepo.log
USER 1001

ENTRYPOINT ["/usr/bin/virt-api"]
