ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# These steps are translated from ./cmd/virt-handler/BUILD.bazel
ARG PACKAGE
RUN groupadd -g 107 qemu && useradd -u 107 -g qemu -s /bin/bash qemu
RUN sh -c "dnf config-manager --enable ol9_appstream --enable ol9_UEKR7 && \
    dnf install -y "$PACKAGE" && \
    dnf clean all"
ADD nsswitch.conf /etc/nsswitch.conf

ENTRYPOINT ["/usr/bin/virt-handler"]
