ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG PACKAGE
RUN useradd -d /home/nonroot-user -U -u 1001 -s /bin/bash nonroot-user
RUN case "$PACKAGE" in *.rpm) rpm -ivh "$PACKAGE" ;; *) microdnf install -y "$PACKAGE" ;; esac && microdnf clean all
USER 1001

ENTRYPOINT ["/usr/bin/virt-controller"]
